### ISSUE TITLE
Reach out to Potential Resource persons for #Open Mic - Twitter spaces and #IG Live 

### ISSUE THREAD

**Issue by Ekeneodigwe** [AfrofutureDAO/iteration2.0#29]
## 🗣️ Introduction
I need to reach out to the resource persons for our upcoming #Open Mic events on Twitter spaces and IG Live. The resource persons will be responsible for providing valuable insights and sharing their expertise on the topics that we'll be discussing during the events

## 🧳 Objective
To provide in-depth analysis of all conversations

## 👣 Subtasks/actions to be taken

- [x] Identify potential resource persons based on the topics of discussion.

- [x] Create a list of potential resource persons and their contact information.

- [x] Reach out to potential resource persons via email or social media.

- [x] Provide details about the event, including the date, time, topic of discussion, and expected duration.

- [x] Explain the role of the resource persons and the benefits of participating in the event.

- [x] Follow up with the resource persons to confirm their availability and participation.

## 👓 Reviewer 
@dadaboipelo & @mrbrookg

**Comment by Ekeneodigwe** [comment]
This is a continuous issue recurring every week

**Comment by Ekeneodigwe** [comment]
> ## 🗣️ Introduction
> I need to reach out to the resource persons for our upcoming #Open Mic events on Twitter spaces and IG Live. The resource persons will be responsible for providing valuable insights and sharing their expertise on the topics that we'll be discussing during the events
> 
> ## 🧳 Objective
> To provide in-depth analysis of all conversations
> 
> ## 👣 Subtasks/actions to be taken
> * [x]  Identify potential resource persons based on the topics of discussion.
> * [x]  Create a list of potential resource persons and their contact information.
> * [x]  Reach out to potential resource persons via email or social media.
> * [x]  Provide details about the event, including the date, time, topic of discussion, and expected duration.
> * [x]  Explain the role of the resource persons and the benefits of participating in the event.
> * [x]  Follow up with the resource persons to confirm their availability and participation.
> 
> ## 👓 Reviewer
> @dadaboipelo & @mrbrookg
> 
> ## 🧶 Supporting Doc/ Link

This is a recurring issue every week
